"use client";

import { useEffect, useMemo, useRef, useState } from "react";

import type { AlertEvent } from "@/lib/alerts";
import { formatEatClock } from "@/lib/format";

interface WhatsappSimulatorProps {
  /** Events routed to the WhatsApp channel, newest first. */
  events: AlertEvent[];
    /** Milliseconds between simulated deliveries. */
  intervalMs?: number;
}

/** Messages shown before the feed starts ticking. */
const OPEN_ON_LOAD = 3;

/**
 * A phone showing the pushes as they land.
 *
 * Events are revealed one at a time on a timer rather than rendered all at once,
 * because the point of the panel is to show what an artist actually experiences:
 * a message arriving the moment a play is verified, not a report at the end of
 * the day. The copy is generated by `whatsappMessage`, the same function a real
 * gateway would call.
 */
export function WhatsappSimulator({ events, intervalMs = 2600 }: WhatsappSimulatorProps) {
  // Oldest first, so the chat reads top to bottom like a real thread.
  const chronological = useMemo(() => [...events].reverse(), [events]);

  const [revealCount, setRevealCount] = useState(OPEN_ON_LOAD);
  const [isLive, setIsLive] = useState(true);
  const scrollerRef = useRef<HTMLDivElement>(null);

  // Clamped at render: when a rule change shrinks the stream the view follows it
  // without an effect having to reset the counter.
  const revealed = Math.min(revealCount, chronological.length);

  useEffect(() => {
    if (!isLive) return;
    if (revealed >= chronological.length) return;

    const timer = window.setTimeout(() => setRevealCount((n) => n + 1), intervalMs);
    return () => window.clearTimeout(timer);
  }, [isLive, revealed, chronological.length, intervalMs]);

  // Keep the newest message in view.
  useEffect(() => {
    const el = scrollerRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [revealed]);

  const visible = chronological.slice(0, revealed);
  const last = visible[visible.length - 1];

  return (
    <section className="panel p-4" aria-labelledby="phone-heading">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h2 id="phone-heading" className="text-sm font-semibold tracking-tight">
            Live delivery
          </h2>
          <p className="mt-1 text-xs text-muted">
            What the rights holder sees on their handset as plays verify.
          </p>
        </div>

        <button
          type="button"
          onClick={() => setIsLive((live) => !live)}
          aria-pressed={isLive}
          className={isLive ? "btn" : "btn btn-primary"}
        >
          {isLive ? "Pause feed" : "Resume feed"}
        </button>
      </div>

      <div className="mt-4 flex justify-center">
        <div
          className="w-[320px] overflow-hidden rounded-[28px] border border-line bg-background shadow-xl"
          role="log"
          aria-label="Simulated WhatsApp alerts"
          aria-live="polite"
        >
          {/* Status bar */}
          <div className="flex items-center justify-between bg-surface px-4 py-1.5 font-mono text-[10px] text-muted">
            <span>{last ? formatEatClock(last.atIso).replace(" EAT", "") : "15:42"}</span>
            <span className="flex items-center gap-1">
              <span aria-hidden>●●●●</span>
              <span aria-hidden>📶</span>
            </span>
          </div>

          {/* Chat header */}
          <div className="flex items-center gap-2 border-b border-line bg-surface px-3 py-2">
            <span
              className="flex h-8 w-8 items-center justify-center rounded-full bg-brand text-xs font-bold text-brand-ink"
              aria-hidden
            >
              ES
            </span>
            <div className="min-w-0">
              <p className="truncate text-xs font-semibold">East Sound Alerts</p>
              <p className="truncate text-[10px] text-accent">online</p>
            </div>
          </div>

          {/* Messages */}
          <div
            ref={scrollerRef}
            className="h-[380px] space-y-2 overflow-y-auto bg-surface-2 p-3"
            style={{
              backgroundImage:
                "radial-gradient(color-mix(in srgb, var(--line) 45%, transparent) 1px, transparent 1px)",
              backgroundSize: "14px 14px",
            }}
          >
            {visible.length === 0 ? (
              <p className="pt-16 text-center text-[11px] text-muted">
                No WhatsApp alerts yet. Switch a recording on to the left.
              </p>
            ) : null}

            {visible.map((event, i) => (
              <div key={event.id} className="flex justify-end">
                <div
                  className="max-w-[85%] rounded-lg rounded-br-none px-3 py-2 text-[11px] leading-relaxed shadow-sm"
                  style={{ background: "#1f6f4a", color: "#eafff4" }}
                >
                  <p className="whitespace-pre-wrap break-words">{event.message}</p>
                  <p className="mt-1 flex items-center justify-end gap-1 text-[9px] opacity-80">
                    {formatEatClock(event.atIso).replace(" EAT", "")}
                    <span aria-hidden>{i === visible.length - 1 ? "✓✓" : "✓✓"}</span>
                  </p>
                </div>
              </div>
            ))}

            {isLive && revealed < chronological.length ? (
              <div className="flex justify-end">
                <span className="rounded-lg px-3 py-2 text-[11px] text-muted" style={{ background: "var(--surface)" }}>
                  typing…
                </span>
              </div>
            ) : null}
          </div>

          {/* Composer, inert — this is a one-way alert channel. */}
          <div className="flex items-center gap-2 border-t border-line bg-surface px-3 py-2">
            <span className="flex-1 rounded-full border border-line px-3 py-1.5 text-[11px] text-muted">
              Message East Sound Alerts
            </span>
            <span
              className="flex h-7 w-7 items-center justify-center rounded-full bg-accent text-xs text-brand-ink"
              aria-hidden
            >
              ➤
            </span>
          </div>
        </div>
      </div>

      <p className="mt-3 text-center text-[11px] text-muted">
        {visible.length} of {chronological.length} messages shown. Delivery is simulated — no
        WhatsApp Business API session is connected.
      </p>
    </section>
  );
}
